name: Document Workflow
description: Structured document creation process
title: "[DOC] "
labels: ["documentation"]
assignees: []
body:




  - type: dropdown
    id: author
    attributes:
      label: Author
      description: Select document author
      multiple: true
      options:
        - "@team-member-1"
        - "@team-member-2" 
        - "@team-member-3"
        - "@team-member-4"
        - "@team-member-5"
        - "@team-member-6"
    validations:
      required: true
      
  - type: dropdown
    id: reviewer
    attributes:
      label: Reviewer
      description: Select document reviewer
      multiple: true
      options:
        - "@team-member-1"
        - "@team-member-2"
        - "@team-member-3" 
        - "@team-member-4"
        - "@team-member-5"
        - "@team-member-6"
    validations:
      required: true
      
  - type: dropdown
    id: validator
    attributes:
      label: Validator
      description: Select document validator
      multiple: true
      options:
        - "@team-member-1"
        - "@team-member-2"
        - "@team-member-3"
        - "@team-member-4"
        - "@team-member-5"
        - "@team-member-6"
    validations:
      required: true









  - type: dropdown
    id: document_type
    attributes:
      label: Document Type
      description: Select document classification
      options:
        - Verbale
        - Piano di Progetto
        - Analisi Requisiti
        - Specifica Tecnica
        - Manuale Utente
        - Norme di Progetto
        - Glossario
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Set document priority level
      options:
        - "🔴 HIGH - Critical path, immediate attention"
        - "🟡 MEDIUM - Standard priority"  
        - "🟢 LOW - Background, when available"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity Level
      description: Determines role assignment method
      options:
        - "SIMPLE - Use queue rotation system"
        - "COMPLEX - Flexible role assignment" 
        - "EMERGENCY - Fast-track procedure"
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: Target Completion Date
      description: Format YYYY-MM-DD
      placeholder: "2024-12-01"
    validations:
      required: true

  - type: textarea
    id: workflow_states
    attributes:
      label: "📋 Workflow State Definitions"
      description: "Reference for state requirements"
      value: |
        ## Backlog Requirements
        - Priority classification set
        - Dependencies mapped  
        - Effort estimation completed
        - Assignment deadline defined

        ## In Progress Requirements
        - Daily progress updates in comments
        - Blocked status reported within 4h
        - Weekly progress report every Friday
        - Minimum 2 peer check-ins per week

        ## In Review Requirements (Max 48h)
        - Technical accuracy checklist
        - Formatting compliance verification  
        - Content completeness assessment
        - Quality score 1-5 in comments

        ## In Validazione Requirements (Max 24h)
        - Final approval criteria verification
        - Stakeholder alignment confirmation
        - Release readiness assessment
        - Re-work estimation if rejected

  - type: textarea
    id: document_details
    attributes:
      label: Document Specifics
      description: Core document information
      placeholder: |
        Purpose: 
        Target Audience: 
        Related Documents: 
        Success Criteria:
        Special Requirements:

  - type: checkboxes
    id: initial_requirements
    attributes:
      label: Pre-flight Checklist
      description: Requirements before starting work
      options:
        - label: Document template selected and verified
        - label: Role assignments confirmed per complexity level
        - label: Dependencies identified and linked
        - label: Success criteria clearly defined
        - label: Reviewers/validators availability confirmed
